[package]
name = "book-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
contracts = { package = "rust", path = "../contracts/gen/rust" }
tokio = {version = "1.46.1", features = ["rt-multi-thread", "macros"] }
tonic = "0.13.1"
